auto: true
server: true
exclude: README.md, .gitignore
permalink: none
baseurl: 
url: http://codersociety.org
hashtag: '#codersociety OR #coder-society OR #codersocietysea OR #codersocietypdx OR #codersocietysfo OR #codersocietyeug OR @codersociety'
github_login: 'codersociety'
github_repo: 'codersociety.github.com'
github_lanaguage: 'JavaScript'